:concurrency: 2
:queues:
  - default
  - active_storage_analysis
  - active_storage_purge
  - user_authentication_mailers
  - user_password_reset_mailers
  - user_withdrawaled
  - popular_storage_board_statistics
  - popular_storage_board_collection
  - google_issue_keyword_scrap
  - zum_issue_keyword_scarp_job
  - community_issue_keyword_scrap
:limits:
  default: 1
  popular_storage_board_statistics: 1
  popular_storage_board_collection: 1